Repository CMPUT301W23T33/QR-Quest, pull requests merged in 2023-03, with the labels that each got.

#66 Issues/39 improvised
  code/app/build.gradle
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/qrquest/Camera.java
  code/app/src/main/java/com/example/qrquest/CameraActivity.java
  code/app/src/main/java/com/example/qrquest/Info.java
  code/app/src/main/java/com/example/qrquest/QRCode.java
  code/app/src/main/res/drawable/baseline_person_big.xml
  code/app/src/main/res/drawable/rounded_bottom_corners.xml
  code/app/src/main/res/drawable/rounded_top_corners_small.xml
  code/app/src/main/res/layout/activity_camera.xml
  code/app/src/main/res/layout/camera_screen.xml
  code/app/src/main/res/layout/edit_profile.xml
  code/app/src/main/res/layout/profile_screen.xml
  code/app/src/main/res/layout/qr_code_display.xml
  code/app/src/main/res/navigation/nav_graph_camera.xml
  code/app/src/main/res/values/strings.xml
  code/app/src/main/res/values/styles.xml
  code/gradlew
Labels: enhancement

#79 Issues/2-improvised
  code/app/src/main/java/com/example/qrquest/EditProfileFragment.java
  code/app/src/main/java/com/example/qrquest/HighestScoreRank.java
  code/app/src/main/java/com/example/qrquest/MainActivity.java
  code/app/src/main/java/com/example/qrquest/MainFragment.java
  code/app/src/main/java/com/example/qrquest/MainRepository.java
  code/app/src/main/java/com/example/qrquest/MainViewModel.java
  code/app/src/main/java/com/example/qrquest/Player.java
  code/app/src/main/java/com/example/qrquest/ProfileFragment.java
  code/app/src/main/java/com/example/qrquest/QRCodeHistory.java
  code/app/src/main/java/com/example/qrquest/QRHistoryAdapter.java
  code/app/src/main/java/com/example/qrquest/QRHistoryViewHolder.java
  code/app/src/main/java/com/example/qrquest/Rank.java
  code/app/src/main/java/com/example/qrquest/ReusableRank.java
  code/app/src/main/java/com/example/qrquest/ScannedNumberRank.java
  code/app/src/main/java/com/example/qrquest/TotalScoreRank.java
  code/app/src/main/res/layout/activity_main.xml
  code/app/src/main/res/layout/fragment_main.xml
  code/app/src/main/res/layout/profile_screen.xml
  code/app/src/main/res/layout/qr_code_display.xml
  code/app/src/main/res/navigation/nav_graph_main.xml
  code/app/src/main/res/values/strings.xml
Labels: enhancement

#84 Issues/81
  code/app/src/main/java/com/example/qrquest/PromptLocationFragment.java
  code/app/src/main/res/values/strings.xml
Labels: bug

#110 Issues/18
  app/src/androidTest/java/com/example/qrquest/ActivityAndFragmentTest.java
  app/src/main/java/com/example/qrquest/AddCommentFragment.java
  app/src/main/java/com/example/qrquest/Comment.java
  app/src/main/java/com/example/qrquest/CommentAdapter.java
  app/src/main/java/com/example/qrquest/CommentViewHolder.java
  app/src/main/java/com/example/qrquest/EditQRFragment.java
  app/src/main/java/com/example/qrquest/HighestScoreRank.java
  app/src/main/java/com/example/qrquest/History.java
  app/src/main/java/com/example/qrquest/HistoryAdapter.java
  app/src/main/java/com/example/qrquest/HistoryViewHolder.java
  app/src/main/java/com/example/qrquest/LeaderboardActivity.java
  app/src/main/java/com/example/qrquest/LeaderboardFragment.java
  app/src/main/java/com/example/qrquest/LeaderboardRepository.java
  app/src/main/java/com/example/qrquest/LeaderboardViewModel.java
  app/src/main/java/com/example/qrquest/MainRepository.java
  app/src/main/java/com/example/qrquest/MainViewModel.java
  app/src/main/java/com/example/qrquest/ProfileFragment.java
  app/src/main/java/com/example/qrquest/QRDisplayFragment.java
  app/src/main/java/com/example/qrquest/QRDisplayRepository.java
  app/src/main/java/com/example/qrquest/QRDisplayViewModel.java
  app/src/main/java/com/example/qrquest/QRHistoryAdapter.java
  app/src/main/java/com/example/qrquest/Rank.java
  app/src/main/java/com/example/qrquest/RegionalHighestScoreRank.java
  app/src/main/java/com/example/qrquest/ScannedNumberRank.java
  app/src/main/java/com/example/qrquest/TotalScoreRank.java
  app/src/main/res/layout/comment_display.xml
  app/src/test/java/com/example/qrquest/CommentTest.java
  app/src/test/java/com/example/qrquest/HighestScoreRankTest.java
  app/src/test/java/com/example/qrquest/HistoryTest.java
  app/src/test/java/com/example/qrquest/InfoTest.java
  app/src/test/java/com/example/qrquest/PlayerTest.java
  app/src/test/java/com/example/qrquest/QRCodeTest.java
  app/src/test/java/com/example/qrquest/RankTest.java
  app/src/test/java/com/example/qrquest/RegionalHighestScoreRankTest.java
  app/src/test/java/com/example/qrquest/ScannedNumberRankTest.java
  app/src/test/java/com/example/qrquest/TotalScoreRankTest.java
  app/src/test/java/com/example/qrquest/UtilitiesTest.java
Labels: enhancement, refinement
